name: MSDO Sample Workflow
on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for federation to Defender for DevOps
  security-events: write # This is required to upload SARIF files

jobs:
  sample:
    name: MSDO on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      
      # Checkout your code repository to scan
    - uses: actions/checkout@v3

    - name: Make some Malware
      shell: pwsh
      run: |
        'X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*' > D:/a/security-devops-action/security-devops-action/definitelyNotMalware.trustme
        Write-Host 'Malware created'


      # Run analyzers
    - name: Run Microsoft Security DevOps Analysis
      uses: microsoft/security-devops-action@v1
      id: msdo

    - name: Check Malware
      shell: pwsh
      run: |
        dir D:/a/security-devops-action/security-devops-action
        Write-Host 'Check complete'
      

      # Upload alerts to the Security tab
    - name: Upload alerts to Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}

      # Upload alerts file as a workflow artifact
    - name: Upload alerts file as a workflow artifact
      uses: actions/upload-artifact@v3
      with:  
        name: alerts
        path: ${{ steps.msdo.outputs.sarifFile }}
